FROM mysql:8.0.23

LABEL mail="moisescaicedo15@gmail.com"
LABEL name="Moises David Caicedo Corena"

ENV MYSQL_USER=USER_MVM_CRUD
ENV MYSQL_PASSWORD=PASS_MVM_CRUD
ENV MYSQL_DATABASE=MVM_CRUD
ENV MYSQL_ROOT_PASSWORD=YOUR_PASS_ROOT
ENV MYSQL_RANDOM_ROOT_PASSWORD=YES
COPY ./scriptsSql/ /docker-entrypoint-initdb.d
EXPOSE 3306:3306